//! Shell integration for the shells Verb hosts.
//!
//! Without it, Verb sees a stream of bytes and can honestly say nothing about what ran inside it.
//! With it, the shell itself reports its working directory and its command boundaries, and Verb's
//! structural events stop being a promise that never fires.
//!
//! Four constraints shape every decision here:
//!
//! * **Hosted shells only.** Verb writes its own files under its own state directory and points a
//!   shell it is launching at them. The user's `~/.zshrc`, `~/.bashrc` and their global environment
//!   are never modified -- a terminal Verb did not start behaves exactly as it did before.
//! * **The user's configuration still loads, first.** The shim sources the real configuration and
//!   only then adds hooks, so prompts, aliases and options survive. Verb appends; it does not
//!   replace.
//! * **Silence stays unknown.** A shell Verb does not know how to instrument is launched exactly as
//!   it would have been, and reports nothing. No fabricated boundaries, no guessed exit codes.
//! * **Nothing durable learns the command text.** The `E` sequence exists for the screen; see
//!   `shell.rs` and `docs/VERB_SESSION_SCHEMA.md`.

use crate::fsutil::atomic_write;
use std::fs;
use std::path::{Path, PathBuf};

/// Verb's shell directory, created owner-only. The bash integration keeps a scratch file here; a
/// shared location such as `/tmp` let another account plant its contents (see `BASH_INTEGRATION`).
fn private_directory(path: &Path) -> Option<PathBuf> {
    fs::create_dir_all(path).ok()?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        let metadata = fs::symlink_metadata(path).ok()?;
        let me = fs::metadata(std::env::var_os("HOME")?).ok()?.uid();
        if !metadata.file_type().is_dir() || metadata.uid() != me {
            return None;
        }
        fs::set_permissions(path, fs::Permissions::from_mode(0o700)).ok()?;
    }
    Some(path.to_path_buf())
}

/// The shells Verb knows how to instrument.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Kind {
    Zsh,
    Bash,
}

impl Kind {
    /// Recognised from the shell's own path. An unrecognised shell is not an error and not a
    /// guess -- it simply gets no instrumentation.
    pub(crate) fn of(shell: &str) -> Option<Self> {
        match Path::new(shell).file_name()?.to_string_lossy().as_ref() {
            "zsh" | "-zsh" => Some(Self::Zsh),
            "bash" | "-bash" => Some(Self::Bash),
            _ => None,
        }
    }
}

/// How to launch a shell so that it reports what it does.
pub(crate) struct Instrumented {
    /// The complete argument list for the shell, replacing the uninstrumented default.
    pub args: Vec<String>,
    /// Environment overrides for the child only.
    pub env: Vec<(String, String)>,
}

/// Prepares integration for `shell`, or `None` when Verb does not know that shell.
///
/// `directory` is Verb's own state directory; everything written lives under it.
pub(crate) fn prepare(shell: &str, directory: &Path) -> Option<Instrumented> {
    let kind = Kind::of(shell)?;
    let root = private_directory(&directory.join("shell"))?;

    match kind {
        Kind::Zsh => {
            // zsh reads its startup files from ZDOTDIR, so Verb points it at a directory of shims
            // that source the user's real files first. Every file zsh might read gets one, or the
            // ones without a shim would simply stop being read.
            let home = std::env::var("HOME").unwrap_or_default();
            let original = std::env::var("ZDOTDIR").unwrap_or(home);
            let zdotdir = root.join("zsh");
            fs::create_dir_all(&zdotdir).ok()?;
            // Atomic: two Verb processes launching shells at once must not interleave a shim.
            atomic_write(
                &zdotdir.join("verb-integration.zsh"),
                ZSH_INTEGRATION.as_bytes(),
            )
            .ok()?;

            for file in ["zshenv", "zprofile", "zshrc", "zlogin"] {
                let shim = format!(
                    "# Generated by Verb for a shell it is hosting. Not installed into your shell.\n\
                     VERB_ZDOTDIR_ORIGINAL=\"{original}\"\n\
                     [ -f \"$VERB_ZDOTDIR_ORIGINAL/.{file}\" ] && \
                     ZDOTDIR=\"$VERB_ZDOTDIR_ORIGINAL\" . \"$VERB_ZDOTDIR_ORIGINAL/.{file}\"\n\
                     {}",
                    if file == "zshrc" {
                        // Hooks are added after the user's configuration, so anything they set is
                        // already in place -- and their prompt is left exactly as they defined it.
                        format!(". \"{}/verb-integration.zsh\"\n", zdotdir.display())
                    } else {
                        String::new()
                    }
                );
                atomic_write(&zdotdir.join(format!(".{file}")), shim.as_bytes()).ok()?;
            }

            Some(Instrumented {
                // Unchanged from an ordinary interactive login shell; ZDOTDIR does the work.
                args: vec!["-i".to_owned(), "-l".to_owned()],
                env: vec![
                    ("ZDOTDIR".to_owned(), zdotdir.display().to_string()),
                    ("VERB_ZDOTDIR_ORIGINAL".to_owned(), original),
                    ("VERB_SHELL_DIR".to_owned(), zdotdir.display().to_string()),
                ],
            })
        }
        Kind::Bash => {
            let rc = root.join("verb-integration.bash");
            atomic_write(&rc, BASH_INTEGRATION.as_bytes()).ok()?;
            Some(Instrumented {
                // --init-file replaces ~/.bashrc for this shell only, and applies to interactive
                // non-login shells -- so this is `-i` rather than `-il`. The file sources the
                // user's own configuration before doing anything else.
                // Long options first: bash 3.2, which is what macOS ships, rejects `-i --init-file`
                // with "--: invalid option".
                args: vec![
                    "--init-file".to_owned(),
                    rc.display().to_string(),
                    "-i".to_owned(),
                ],
                env: vec![("VERB_SHELL_DIR".to_owned(), root.display().to_string())],
            })
        }
    }
}

/// Emitted by both scripts. `A`/`B`/`C`/`D` are the command-boundary sequence Verb's scanner reads,
/// `E` is the command line (volatile), and OSC 7 is the working directory.
const ZSH_INTEGRATION: &str = r#"# Generated by Verb for shells it hosts. Never installed into your shell configuration.
#
# Emits the shell-integration sequences Verb reads: OSC 7 for the working directory and
# OSC 633 A/B/C/D/E for prompt and command boundaries. Nothing else about your shell changes;
# your prompt is whatever you configured it to be.

__verb_osc() { printf '\033]%s\007' "$1"; }

# zsh's history file follows ZDOTDIR, which Verb has pointed at its own directory. Left alone, the
# user's shell history would be split off into Verb's storage -- which is both the wrong place for
# their history and command text inside Verb's state, which the contract forbids. Put it back.
case "$HISTFILE" in
  "$VERB_SHELL_DIR"/*|"") HISTFILE="$VERB_ZDOTDIR_ORIGINAL/.zsh_history" ;;
esac

__verb_cwd() { __verb_osc "7;file://${HOST:-}${PWD}"; }

__verb_escape() {
  local value=${1//\\/\\\\}
  value=${value//;/\\x3b}
  value=${value//$'\n'/\\x0a}
  printf '%s' "$value"
}

__verb_preexec() {
  __verb_osc "633;E;$(__verb_escape "$1")"
  __verb_osc "633;C"
}

__verb_precmd() {
  # Not `status`: zsh makes that a read-only alias for $?.
  local verb_status=$?
  __verb_osc "633;D;$verb_status"
  __verb_cwd
  __verb_osc "633;A"
  __verb_osc "633;B"
  return $verb_status
}

autoload -Uz add-zsh-hook 2>/dev/null
if command -v add-zsh-hook >/dev/null 2>&1; then
  add-zsh-hook preexec __verb_preexec
  add-zsh-hook precmd __verb_precmd
else
  precmd_functions+=(__verb_precmd)
  preexec_functions+=(__verb_preexec)
fi
__verb_cwd
"#;

const BASH_INTEGRATION: &str = r#"# Generated by Verb for shells it hosts. Never installed into your shell configuration.
#
# Loads your own configuration first, then adds the hooks Verb reads: OSC 7 for the working
# directory and OSC 633 A/B/C/D/E for prompt and command boundaries.

if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
elif [ -f "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

__verb_osc() { printf '\033]%s\007' "$1"; }

__verb_cwd() { __verb_osc "7;file://${HOSTNAME:-}${PWD}"; }

__verb_escape() {
  local value=${1//\\/\\\\}
  value=${value//;/\\x3b}
  value=${value//$'\n'/\\x0a}
  printf '%s' "$value"
}

# The command as the user typed it. $BASH_COMMAND has already been through alias expansion, so on
# most Linux systems `ls` arrives as `ls --color=auto`. The longest alias whose expansion starts the
# command is folded back to its name. bash 3.2 (macOS) has no BASH_ALIASES and keeps the expanded
# form, which is still the command that ran.
__verb_take_typed() {
  __verb_typed_line=$BASH_COMMAND
  [ "${BASH_VERSINFO[0]:-0}" -ge 4 ] || return 0
  local name value best="" best_value=""
  for name in "${!BASH_ALIASES[@]}"; do
    value=${BASH_ALIASES[$name]}
    case "$__verb_typed_line" in
      "$value" | "$value "*)
        if [ ${#value} -gt ${#best_value} ]; then
          best=$name
          best_value=$value
        fi
        ;;
    esac
  done
  if [ -n "$best" ]; then
    __verb_typed_line=$best${__verb_typed_line#"$best_value"}
  fi
}

# DEBUG fires before each command; the guard keeps it to the command the user actually ran rather
# than every function call inside the prompt.
#
# A prior DEBUG trap runs first, unchanged. bash allows exactly one, so installing Verb's without
# looking would silently disable whatever the user (or a tool they use) had already set up.
__verb_prior_debug=""

__verb_debug() {
  if [ -n "$__verb_prior_debug" ]; then
    eval "$__verb_prior_debug"
  fi
  if [ -n "$COMP_LINE" ] || [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ]; then
    return
  fi
  # Verb's own plumbing is not something the user ran.
  case "$BASH_COMMAND" in
    __verb_*) return ;;
  esac
  if [ "$__verb_running" = "1" ]; then
    return
  fi
  __verb_running=1
  __verb_take_typed
  __verb_osc "633;E;$(__verb_escape "$__verb_typed_line")"
  __verb_osc "633;C"
}

__verb_prompt() {
  local verb_status=$?
  if [ "$__verb_running" = "1" ]; then
    __verb_osc "633;D;$verb_status"
    __verb_running=0
  fi
  __verb_cwd
  __verb_osc "633;A"
  __verb_osc "633;B"
  return $verb_status
}

# The prompt hook is installed either way: even without command boundaries, the working directory
# is still a fact the shell can report.
if [ -n "$PROMPT_COMMAND" ]; then
  PROMPT_COMMAND="__verb_prompt; $PROMPT_COMMAND"
else
  PROMPT_COMMAND="__verb_prompt"
fi
__verb_cwd

# Installing the DEBUG hook, at top level, last, and never inside a function.
#
# bash treats DEBUG specially in three ways that all bite here. A trap set inside a function is gone
# again when that function returns. `trap -p` inside a command substitution reports nothing, because
# the subshell has had its DEBUG trap reset -- so the obvious "is there already a trap?" check
# answers no every time and Verb would clobber the user's. And a trap installed before the rest of
# this file has finished traces Verb's own remaining lines. Hence: read the existing trap through a
# file, which `trap -p` writes from the current shell; decide here rather than in a function; and
# install after everything else has run.
#
# The file lives in Verb's owner-only shell directory, never in a shared /tmp: there, another account
# could create `verb-debug-trap.<pid>` first, the write here would fail quietly, and the read would
# return *their* trap -- which is then eval'd before every command. If the private directory is not
# there, Verb does not read a trap at all and installs no hook.
__verb_existing_debug=""
__verb_install=1
if [ -n "$VERB_SHELL_DIR" ] && [ -d "$VERB_SHELL_DIR" ] && [ -O "$VERB_SHELL_DIR" ]; then
  __verb_trap_file="$VERB_SHELL_DIR/debug-trap.$$"
  rm -f "$__verb_trap_file"
  # Not in a subshell: a subshell has its DEBUG trap reset and would report none.
  __verb_umask=$(umask)
  umask 077
  if trap -p DEBUG > "$__verb_trap_file" 2>/dev/null && [ -O "$__verb_trap_file" ]; then
    IFS= read -r __verb_existing_debug < "$__verb_trap_file"
  else
    __verb_install=0
  fi
  umask "$__verb_umask"
  unset __verb_umask
  rm -f "$__verb_trap_file"
  unset __verb_trap_file
else
  __verb_install=0
fi

if [ -n "$__verb_existing_debug" ]; then
  case "$__verb_existing_debug" in
    "trap -- '"*"' DEBUG")
      __verb_prior_debug=${__verb_existing_debug#trap -- \'}
      __verb_prior_debug=${__verb_prior_debug%\' DEBUG}
      # A quote in the body means `trap -p` handed it back re-escaped, and what came back is no
      # longer the command the user wrote. Conservative on purpose: keep their trap exactly as it is
      # and do without command boundaries -- reduced observability, never a rewritten trap, and
      # never a fabricated boundary.
      case "$__verb_prior_debug" in
        *\'*)
          __verb_prior_debug=""
          __verb_install=0
          ;;
      esac
      ;;
    *)
      # An unfamiliar shape. Same rule: leave it alone.
      __verb_install=0
      ;;
  esac
fi
unset __verb_existing_debug

# The trap is the very last thing to run, so nothing of Verb's own is left to trace.
if [ "$__verb_install" = "1" ]; then
  unset __verb_install
  trap '__verb_debug' DEBUG
else
  unset __verb_install
fi
"#;

#[cfg(test)]
mod tests {
    #[test]
    fn the_bash_integration_never_uses_a_shared_temporary_directory() {
        // Another account can pre-create files in /tmp; whatever the script reads back is eval'd.
        let code: Vec<&str> = super::BASH_INTEGRATION
            .lines()
            .filter(|line| !line.trim_start().starts_with('#'))
            .collect();
        assert!(!code.iter().any(|line| line.contains("/tmp")));
        assert!(!code.iter().any(|line| line.contains("TMPDIR")));
        assert!(super::BASH_INTEGRATION.contains("-O \"$VERB_SHELL_DIR\""));
    }

    /// The labels a real bash reports through `OSC 633;E` for the given input.
    fn bash_labels(bashrc: &str, input: &str) -> Vec<String> {
        use std::io::Write;
        use std::os::unix::fs::PermissionsExt;
        let home = std::env::temp_dir().join(format!("verb-bash-labels-{}", std::process::id()));
        let shell_dir = home.join("shell");
        std::fs::create_dir_all(&shell_dir).unwrap();
        std::fs::set_permissions(&shell_dir, std::fs::Permissions::from_mode(0o700)).unwrap();
        std::fs::write(home.join(".bashrc"), bashrc).unwrap();
        let rc = shell_dir.join("verb-integration.bash");
        std::fs::write(&rc, super::BASH_INTEGRATION).unwrap();
        let mut child = std::process::Command::new("bash")
            .args(["--init-file", rc.to_str().unwrap(), "-i"])
            .env("HOME", &home)
            .env("HISTFILE", "/dev/null")
            .env("VERB_SHELL_DIR", &shell_dir)
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        child
            .stdin
            .take()
            .unwrap()
            .write_all(input.as_bytes())
            .unwrap();
        let out = child.wait_with_output().unwrap();
        let _ = std::fs::remove_dir_all(&home);
        String::from_utf8_lossy(&out.stdout)
            .split("\x1b]633;E;")
            .skip(1)
            .map(|rest| rest.split('\x07').next().unwrap_or_default().to_owned())
            .collect()
    }

    #[test]
    fn bash_reports_a_command_as_typed_not_as_its_alias_expansion() {
        let modern = std::process::Command::new("bash")
            .args(["-c", "[ \"${BASH_VERSINFO[0]}\" -ge 4 ]"])
            .status()
            .is_ok_and(|status| status.success());
        let labels = bash_labels(
            "alias ls='ls --color=auto'\nalias ll='ls -alF'\n",
            "ls /verb-missing\nls /verb-missing\nll /verb-missing\necho done\nexit\n",
        );
        if modern {
            // Ubuntu's default ~/.bashrc has exactly this alias; the expanded `--color=auto` would
            // read as a variable assignment and the command would go unlabelled.
            assert_eq!(
                labels,
                [
                    "ls /verb-missing",
                    "ls /verb-missing",
                    "ls -alF /verb-missing",
                    "echo done",
                    "exit"
                ]
            );
        } else {
            // bash 3.2 has no BASH_ALIASES; it reports the command that ran.
            assert_eq!(labels.len(), 5, "{labels:?}");
            assert_eq!(labels[3], "echo done");
        }
    }
}
