//! Shell integration for the shells Verb hosts.
//!
//! Without it, Verb sees a stream of bytes and can honestly say nothing about what ran inside it.
//! With it, the shell itself reports its working directory and its command boundaries, and Verb's
//! structural events stop being a promise that never fires.
//!
//! Four constraints shape every decision here:
//!
//! * **Hosted shells only.** Verb writes its own files under its own state directory and points a
//!   shell it is launching at them. The user's `~/.zshrc`, `~/.bashrc` and their global environment
//!   are never modified -- a terminal Verb did not start behaves exactly as it did before.
//! * **The user's configuration still loads, first.** The shim sources the real configuration and
//!   only then adds hooks, so prompts, aliases and options survive. Verb appends; it does not
//!   replace.
//! * **Silence stays unknown.** A shell Verb does not know how to instrument is launched exactly as
//!   it would have been, and reports nothing. No fabricated boundaries, no guessed exit codes.
//! * **Nothing durable learns the command text.** The `E` sequence exists for the screen; see
//!   `shell.rs` and `docs/VERB_SESSION_SCHEMA.md`.

use std::fs;
use std::path::Path;

/// The shells Verb knows how to instrument.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Kind {
    Zsh,
    Bash,
}

impl Kind {
    /// Recognised from the shell's own path. An unrecognised shell is not an error and not a
    /// guess -- it simply gets no instrumentation.
    pub(crate) fn of(shell: &str) -> Option<Self> {
        match Path::new(shell).file_name()?.to_string_lossy().as_ref() {
            "zsh" | "-zsh" => Some(Self::Zsh),
            "bash" | "-bash" => Some(Self::Bash),
            _ => None,
        }
    }
}

/// How to launch a shell so that it reports what it does.
pub(crate) struct Instrumented {
    /// The complete argument list for the shell, replacing the uninstrumented default.
    pub args: Vec<String>,
    /// Environment overrides for the child only.
    pub env: Vec<(String, String)>,
}

/// Prepares integration for `shell`, or `None` when Verb does not know that shell.
///
/// `directory` is Verb's own state directory; everything written lives under it.
pub(crate) fn prepare(shell: &str, directory: &Path) -> Option<Instrumented> {
    let kind = Kind::of(shell)?;
    let root = directory.join("shell");
    fs::create_dir_all(&root).ok()?;

    match kind {
        Kind::Zsh => {
            // zsh reads its startup files from ZDOTDIR, so Verb points it at a directory of shims
            // that source the user's real files first. Every file zsh might read gets one, or the
            // ones without a shim would simply stop being read.
            let home = std::env::var("HOME").unwrap_or_default();
            let original = std::env::var("ZDOTDIR").unwrap_or(home);
            let zdotdir = root.join("zsh");
            fs::create_dir_all(&zdotdir).ok()?;
            fs::write(zdotdir.join("verb-integration.zsh"), ZSH_INTEGRATION).ok()?;

            for file in ["zshenv", "zprofile", "zshrc", "zlogin"] {
                let shim = format!(
                    "# Generated by Verb for a shell it is hosting. Not installed into your shell.\n\
                     VERB_ZDOTDIR_ORIGINAL=\"{original}\"\n\
                     [ -f \"$VERB_ZDOTDIR_ORIGINAL/.{file}\" ] && \
                     ZDOTDIR=\"$VERB_ZDOTDIR_ORIGINAL\" . \"$VERB_ZDOTDIR_ORIGINAL/.{file}\"\n\
                     {}",
                    if file == "zshrc" {
                        // Hooks are added after the user's configuration, so anything they set is
                        // already in place -- and their prompt is left exactly as they defined it.
                        format!(". \"{}/verb-integration.zsh\"\n", zdotdir.display())
                    } else {
                        String::new()
                    }
                );
                fs::write(zdotdir.join(format!(".{file}")), shim).ok()?;
            }

            Some(Instrumented {
                // Unchanged from an ordinary interactive login shell; ZDOTDIR does the work.
                args: vec!["-i".to_owned(), "-l".to_owned()],
                env: vec![
                    ("ZDOTDIR".to_owned(), zdotdir.display().to_string()),
                    ("VERB_ZDOTDIR_ORIGINAL".to_owned(), original),
                    ("VERB_SHELL_DIR".to_owned(), zdotdir.display().to_string()),
                ],
            })
        }
        Kind::Bash => {
            let rc = root.join("verb-integration.bash");
            fs::write(&rc, BASH_INTEGRATION).ok()?;
            Some(Instrumented {
                // --init-file replaces ~/.bashrc for this shell only, and applies to interactive
                // non-login shells -- so this is `-i` rather than `-il`. The file sources the
                // user's own configuration before doing anything else.
                // Long options first: bash 3.2, which is what macOS ships, rejects `-i --init-file`
                // with "--: invalid option".
                args: vec![
                    "--init-file".to_owned(),
                    rc.display().to_string(),
                    "-i".to_owned(),
                ],
                env: Vec::new(),
            })
        }
    }
}

/// Emitted by both scripts. `A`/`B`/`C`/`D` are the command-boundary sequence Verb's scanner reads,
/// `E` is the command line (volatile), and OSC 7 is the working directory.
const ZSH_INTEGRATION: &str = r#"# Generated by Verb for shells it hosts. Never installed into your shell configuration.
#
# Emits the shell-integration sequences Verb reads: OSC 7 for the working directory and
# OSC 633 A/B/C/D/E for prompt and command boundaries. Nothing else about your shell changes;
# your prompt is whatever you configured it to be.

__verb_osc() { printf '\033]%s\007' "$1"; }

# zsh's history file follows ZDOTDIR, which Verb has pointed at its own directory. Left alone, the
# user's shell history would be split off into Verb's storage -- which is both the wrong place for
# their history and command text inside Verb's state, which the contract forbids. Put it back.
case "$HISTFILE" in
  "$VERB_SHELL_DIR"/*|"") HISTFILE="$VERB_ZDOTDIR_ORIGINAL/.zsh_history" ;;
esac

__verb_cwd() { __verb_osc "7;file://${HOST:-}${PWD}"; }

__verb_escape() {
  local value=${1//\\/\\\\}
  value=${value//;/\\x3b}
  value=${value//$'\n'/\\x0a}
  printf '%s' "$value"
}

__verb_preexec() {
  __verb_osc "633;E;$(__verb_escape "$1")"
  __verb_osc "633;C"
}

__verb_precmd() {
  # Not `status`: zsh makes that a read-only alias for $?.
  local verb_status=$?
  __verb_osc "633;D;$verb_status"
  __verb_cwd
  __verb_osc "633;A"
  __verb_osc "633;B"
  return $verb_status
}

autoload -Uz add-zsh-hook 2>/dev/null
if command -v add-zsh-hook >/dev/null 2>&1; then
  add-zsh-hook preexec __verb_preexec
  add-zsh-hook precmd __verb_precmd
else
  precmd_functions+=(__verb_precmd)
  preexec_functions+=(__verb_preexec)
fi
__verb_cwd
"#;

const BASH_INTEGRATION: &str = r#"# Generated by Verb for shells it hosts. Never installed into your shell configuration.
#
# Loads your own configuration first, then adds the hooks Verb reads: OSC 7 for the working
# directory and OSC 633 A/B/C/D/E for prompt and command boundaries.

if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
elif [ -f "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

__verb_osc() { printf '\033]%s\007' "$1"; }

__verb_cwd() { __verb_osc "7;file://${HOSTNAME:-}${PWD}"; }

__verb_escape() {
  local value=${1//\\/\\\\}
  value=${value//;/\\x3b}
  value=${value//$'\n'/\\x0a}
  printf '%s' "$value"
}

# DEBUG fires before each command; the guard keeps it to the command the user actually ran rather
# than every function call inside the prompt.
__verb_debug() {
  if [ -n "$COMP_LINE" ] || [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ]; then
    return
  fi
  if [ "$__verb_running" = "1" ]; then
    return
  fi
  __verb_running=1
  __verb_osc "633;E;$(__verb_escape "$BASH_COMMAND")"
  __verb_osc "633;C"
}

__verb_prompt() {
  local verb_status=$?
  if [ "$__verb_running" = "1" ]; then
    __verb_osc "633;D;$verb_status"
    __verb_running=0
  fi
  __verb_cwd
  __verb_osc "633;A"
  __verb_osc "633;B"
  return $verb_status
}

trap '__verb_debug' DEBUG
if [ -n "$PROMPT_COMMAND" ]; then
  PROMPT_COMMAND="__verb_prompt; $PROMPT_COMMAND"
else
  PROMPT_COMMAND="__verb_prompt"
fi
__verb_cwd
"#;
